const GOATsellerCommissions = {
    "90 or above": 9,
    "Between 70-89": 15,
    "Between 50-69": 20,
    "Below 50": 25 
};

const locationSellerFees = {
    "United States": 5,
    "American Samoa": 35,
    "APO/FPO Pacific": 25,
    "APO/FPO Europe": 25,
    "APO/FPO United States": 25,
    "Mariana Islands": 15,
    "Puerto Rico": 8,
    "U.S Virgin Islands": 15,
    "Australia": 8, 
    "Austria": 6, 
    "Belgium": 6, 
    "Bulgaria": 12, 
    "Canada": 5,
    "Mainland China (drop-off)": 10,
    "Mainland China (prepaid shipping)": 15,
    "Croatia": 12,
    "Cyprus": 34, 
    "Czech Republic": 6, 
    "Denmark": 10, 
    "Estonia": 12, 
    "Finland": 10, 
    "France": 6, 
    "Germany": 5,          
    "Greece": 12, 
    "Guam": 25, 
    "Hong Kong": 10, 
    "Hong Kong(drop-off)": 5, 
    "Hungary": 12, 
    "Indonesia": 10, 
    "Ireland": 12,
    "Italy": 8,
    "Japan": 10, 
    "Japan(drop-off)": 5, 
    "Latvia": 12, 
    "Lithuania": 12, 
    "Luxembourg": 10, 
    "Malaysia": 10, 
    "Malta": 24, 
    "Netherlands": 6, 
    "Philippines": 10, 
    "Poland": 6, 
    "Portugal": 12, 
    "Romania": 12, 
    "Singapore": 5, 
    "Slovakia": 6, 
    "Slovenia": 12, 
    "South Korea": 5, 
    "Spain": 8, 
    "Sweden": 10, 
    "Taiwan": 5, 
    "Thailand": 10, 
    "United Kingdom": 5, 
    "Other": 30
}

module.exports = {
    GOATsellerCommissions,
    locationSellerFees
}